### ISSUE TITLE
npm install package

### ISSUE THREAD

**Issue by farahfarah1** [fobo66/algolia-firebase-functions#242]
Cannot find module 'algolia-firebase-functions'
this is my package.json
{
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "scripts": {
    "lint": "eslint .",
    "serve": "firebase emulators:start --only functions",
    "shell": "firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "14"
  },
  "main": "index.js",
  "dependencies": {
    "algolia-firebase-functions": "^4.1.0",
    "algoliasearch": "^4.10.2",
    "firebase-admin": "^9.8.0",
    "firebase-functions": "^3.14.1"
  },
  "devDependencies": {
    "eslint": "^7.6.0",
    "eslint-config-google": "^0.14.0",
    "firebase-functions-test": "^0.2.0"
  },
  "private": true
}

**Comment by fobo66** [comment]
Just installed 'algolia-firebase-functions' via npm, everything was fine. Maybe try again later, or please provide more details, at least npm logs

**Comment by farahfarah1** [comment]
fobbo66 thanks for reply i install the algolia-firebase-fucntions correctly in function directory but when i deploy the function to firebase this error comes out :cannot find module 'algolia-firebase-functions'

**Comment by farahfarah1** [comment]
Error: Cannot find module 'algolia-firebase-functions/'
Require stack:
- /app/index.js

**Comment by fobo66** [comment]
Yeah, I can confirm the issue is here. Looks like on NPM deploy there was no code supplied to NPM actually. Will try to resolve the issue, will let you know once it's OK

**Comment by fobo66** [comment]
Version 4.1.2 should resolve this problem. Please try running `npm update` (or change algolia-firebase-functions version in package.json and run `npm install`) and redeploy your functions

**Comment by fobo66** [comment]
@farahfarah1 Thanks for reporting it!
